### ISSUE TITLE
Sorting on a property that doesn't exist throws ES exception

### ISSUE THREAD

**Issue by jharwig** [v5analytics/visallo#265]
Sort on any property with a clean system shows the error.

```
Caused by: org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[ezTnGAMGTNyQ85sKty8G8w][visallo_vertexium][0]: SearchParseException[[visallo_vertexium][0]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [Failed to parse source [{"from":0,"size":10,"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":{"filters":[{"terms":{"__elementType":["vertex"]}},{"or":{"filters":[{"exists":{"field":"__elementType_00000000000000000000000000000000"}}]}}]}}}},"fields":"__elementType","sort":[{"http://www.example.com#property":{"order":"asc"}}]}]]]; nested: SearchParseException[[visallo_vertexium][0]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [No mapping found for [http://www.example.com#property] in order to sort on]]; }{[ezTnGAMGTNyQ85sKty8G8w][visallo_vertexium][1]: SearchParseException[[visallo_vertexium][1]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [Failed to parse source [{"from":0,"size":10,"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":{"filters":[{"terms":{"__elementType":["vertex"]}},{"or":{"filters":[{"exists":{"field":"__elementType_00000000000000000000000000000000"}}]}}]}}}},"fields":"__elementType","sort":[{"http://www.example.com#property":{"order":"asc"}}]}]]]; nested: SearchParseException[[visallo_vertexium][1]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [No mapping found for [http://www.example.com#property] in order to sort on]]; }{[ezTnGAMGTNyQ85sKty8G8w][visallo_vertexium][2]: SearchParseException[[visallo_vertexium][2]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [Failed to parse source [{"from":0,"size":10,"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":{"filters":[{"terms":{"__elementType":["vertex"]}},{"or":{"filters":[{"exists":{"field":"__elementType_00000000000000000000000000000000"}}]}}]}}}},"fields":"__elementType","sort":[{"http://www.example.com#property":{"order":"asc"}}]}]]]; nested: SearchParseException[[visallo_vertexium][2]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [No mapping found for [http://www.example.com#property] in order to sort on]]; }{[ezTnGAMGTNyQ85sKty8G8w][visallo_vertexium][3]: SearchParseException[[visallo_vertexium][3]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [Failed to parse source [{"from":0,"size":10,"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":{"filters":[{"terms":{"__elementType":["vertex"]}},{"or":{"filters":[{"exists":{"field":"__elementType_00000000000000000000000000000000"}}]}}]}}}},"fields":"__elementType","sort":[{"http://www.example.com#property":{"order":"asc"}}]}]]]; nested: SearchParseException[[visallo_vertexium][3]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [No mapping found for [http://www.example.com#property] in order to sort on]]; }{[ezTnGAMGTNyQ85sKty8G8w][visallo_vertexium][4]: SearchParseException[[visallo_vertexium][4]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [Failed to parse source [{"from":0,"size":10,"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":{"filters":[{"terms":{"__elementType":["vertex"]}},{"or":{"filters":[{"exists":{"field":"__elementType_00000000000000000000000000000000"}}]}}]}}}},"fields":"__elementType","sort":[{"http://www.example.com#property":{"order":"asc"}}]}]]]; nested: SearchParseException[[visallo_vertexium][4]: query[ConstantScore(+cache(__elementType:vertex) +cache(BooleanFilter(_field_names:__elementType_00000000000000000000000000000000)))],from[0],size[10]: Parse Failure [No mapping found for [http://www.example.com#property] in order to sort on]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:237)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:183)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

```

**Comment by EvanOxfeld** [comment]
This may have been fixed in vertexium.

**Comment by nidasid** [comment]
I didn't see any errors or exceptions. Works fine now.
