### ISSUE TITLE
Deleting vertices on workspace with SqlGraph throws 500

### ISSUE THREAD

**Issue by jharwig** [v5analytics/visallo#276]
Add vertex to workspace, then remove.  Upon refresh, the vertex is deleted from workspace. If you select multiple and delete only one is removed on refresh. Seems to hit error after the first (so request throws 500) and any vertices after don't get removed.

SqlGraph, InProcessElasticSearch

```
Caused by: org.elasticsearch.index.engine.DocumentMissingException: [vertexium][0] [element][WORKSPACE_507859c0c6e74db5b8742dfc763f76de_TO_ENTITY_cae832d1941a4a2096f3ec338c8089da]: document missing
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:82)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:176)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:170)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$AsyncSingleAction$1.run(TransportInstanceSingleOperationAction.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by srfarley** [comment]
I'm seeing this too.

**Comment by sfeng88** [comment]
There's a bug in Vertexium's in memory implementation. Looking into it.
